#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

# Clear folders including 0.orig that is not included in CleanFunctions
rm -rf postProcessing-*
rm -f *.csv *.pdf

#------------------------------------------------------------------------------
