#!/bin/bash
cd "${0%/*}" || exit     # Run from this directory
. ../../functions        # Singularity run functions
#------------------------------------------------------------------------------

cleanCase

# Clear folders including 0.orig that is not included in CleanFunctions
rm -rf postProcessing-*
rm -f *.csv *.pdf

#------------------------------------------------------------------------------
