#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

\cp -rf 0.SA 0

# dummy file for post-processing with paraview
touch post.foam

# mesh creation
runApplication blockMesh

runApplication pimpleFoam
